comet:
  model: Unbabel/wmt22-cometkiwi-da
huggingface:
  token: 
  tokenizers_parallelism: false
engines:
  predictionguard:
    api_key: 
    models:
      Hermes-2-Pro-Llama-3-8B:
        languages:
          - arb_Arab
          - ayr_Latn
          - cat_Latn
          - zho_Hans
          - hrv_Latn
          - ces_Latn
          - dan_Latn
          - nld_Latn
          - eng_Latn
          - epo_Latn
          - fin_Latn
          - fra_Latn
          - glg_Latn
          - deu_Latn
          - grn_Latn
          - haw
          - heb_Hebr
          - hin_Deva
          - hmn
          - hun_Latn
          - ind_Latn
          - ita_Latn
          - jpn_Jpan
          - kor_Hang
          - lat
          - lvs_Latn
          - ltz_Latn
          - nob_Latn
          - pes_Arab
          - pol_Latn
          - por_Latn
          - quy_Latn
          - ron_Latn
          - rus_Cyrl
          - sco
          - srp_Cyrl
          - sna_Latn
          - slk_Latn
          - slv_Latn
          - spa_Latn
          - swe_Latn
          - tha_Thai
          - tur_Latn
          - ukr_Cyrl
          - vie_Latn
      Hermes-2-Pro-Mistral-7B:
        languages:
          - arb_Arab
          - ayr_Latn
          - cat_Latn
          - zho_Hans
          - hrv_Latn
          - ces_Latn
          - dan_Latn
          - nld_Latn
          - eng_Latn
          - epo_Latn
          - fin_Latn
          - fra_Latn
          - glg_Latn
          - deu_Latn
          - grn_Latn
          - haw
          - heb_Hebr
          - hin_Deva
          - hmn
          - hun_Latn
          - ind_Latn
          - ita_Latn
          - jpn_Jpan
          - kor_Hang
          - lat
          - lvs_Latn
          - ltz_Latn
          - nob_Latn
          - pes_Arab
          - pol_Latn
          - por_Latn
          - quy_Latn
          - ron_Latn
          - rus_Cyrl
          - sco
          - srp_Cyrl
          - sna_Latn
          - slk_Latn
          - slv_Latn
          - spa_Latn
          - swe_Latn
          - tha_Thai
          - tur_Latn
          - ukr_Cyrl
          - vie_Latn
      Neural-Chat-7B:
        languages:
          - eng_Latn
          - zho_Hans
  deepl:
    api_key: 
    languages:
      - arb_Arab
      - bul_Cyrl
      - zho_Hans
      - ces_Latn
      - dan_Latn
      - nld_Latn
      - eng_Latn
      - est_Latn
      - fin_Latn
      - fra_Latn
      - deu_Latn
      - hun_Latn
      - ind_Latn
      - ita_Latn
      - jpn_Jpan
      - kor_Hang
      - lvs_Latn
      - lit_Latn
      - ell_Grek
      - nob_Latn
      - pol_Latn
      - por_Latn
      - ron_Latn
      - rus_Cyrl
      - slk_Latn
      - slv_Latn
      - spa_Latn
      - swe_Latn
      - tur_Latn
      - ukr_Cyrl
  google_translate:
    project_id: lang-h1
    api_key: 
    languages:
      - afr_Latn
      - als_Latn
      - amh_Ethi
      - arb_Arab
      - hye_Armn
      - asm_Beng
      - ayr_Latn
      - azj_Latn
      - bam_Latn
      - eus_Latn
      - bel_Cyrl
      - ben_Beng
      - bho_Deva
      - bos_Latn
      - bul_Cyrl
      - cat_Latn
      - ceb_Latn
      - zho_Hans
      - zho_Hant
      - hrv_Latn
      - ces_Latn
      - dan_Latn
      - nld_Latn
      - eng_Latn
      - epo_Latn
      - est_Latn
      - ewe_Latn
      - tgl_Latn
      - fin_Latn
      - fra_Latn
      - glg_Latn
      - kat_Geor
      - deu_Latn
      - ell_Grek
      - grn_Latn
      - guj_Gujr
      - hat_Latn
      - hau_Latn
      - haw_Latn
      - heb_Hebr
      - hin_Deva
      - hun_Latn
      - isl_Latn
      - ibo_Latn
      - ilo_Latn
      - ind_Latn
      - gle_Latn
      - ita_Latn
      - jpn_Jpan
      - jav_Latn
      - kan_Knda
      - kaz_Cyrl
      - khm_Khmr
      - kin_Latn
      - kor_Hang
      - kmr_Latn
      - ckb_Arab
      - kir_Cyrl
      - lao_Laoo
      - lvs_Latn
      - lin_Latn
      - lit_Latn
      - lug_Latn
      - ltz_Latn
      - mkd_Cyrl
      - mai_Deva
      - mlg_Latn
      - zsm_Latn
      - mal_Mlym
      - mlt_Latn
      - mri_Latn
      - mar_Deva
      - mni_Beng
      - lus_Latn
      - khk_Cyrl
      - mya_Mymr
      - npi_Deva
      - nob_Latn
      - nya_Latn
      - ory_Orya
      - orm_Latn
      - pbt_Arab
      - pes_Arab
      - pol_Latn
      - por_Latn
      - pan_Guru
      - quy_Latn
      - ron_Latn
      - rus_Cyrl
      - smo_Latn
      - san_Deva
      - gla_Latn
      - nso_Latn
      - srp_Cyrl
      - sot_Latn
      - sna_Latn
      - snd_Arab
      - sin_Sinh
      - slk_Latn
      - slv_Latn
      - som_Latn
      - spa_Latn
      - sun_Latn
      - swh_Latn
      - swe_Latn
      - tgk_Cyrl
      - tam_Taml
      - tat_Cyrl
      - tel_Telu
      - tha_Thai
      - tir_Ethi
      - tso_Latn
      - tur_Latn
      - tuk_Latn
      - aka_Latn
      - ukr_Cyrl
      - urd_Arab
      - uig_Arab
      - uzn_Latn
      - vie_Latn
      - cym_Latn
      - xho_Latn
      - ydd_Hebr
      - yor_Latn
      - zul_Latn
  openai:
    api_key: 
    model: gpt-4
    languages:
      - afr_Latn
      - als_Latn
      - arb_Arab
      - hye_Armn
      - asm_Beng
      - azj_Latn
      - eus_Latn
      - bel_Cyrl
      - ben_Beng
      - bos_Latn
      - bul_Cyrl
      - mya_Mymr
      - cat_Latn
      - zho_Hans
      - hrv_Latn
      - ces_Latn
      - dan_Latn
      - nld_Latn
      - eng_Latn
      - est_Latn
      - fil
      - fin_Latn
      - fra_Latn
      - glg_Latn
      - kat_Geor
      - deu_Latn
      - guj_Gujr
      - hat_Latn
      - hau_Latn
      - heb_Hebr
      - hin_Deva
      - hmn
      - hun_Latn
      - isl_Latn
      - ibo_Latn
      - ind_Latn
      - gle_Latn
      - ita_Latn
      - jpn_Jpan
      - jav_Latn
      - kan_Knda
      - kaz_Cyrl
      - khm_Khmr
      - kin_Latn
      - kor_Hang
      - kmr_Latn
      - lao_Laoo
      - lvs_Latn
      - lit_Latn
      - ltz_Latn
      - mkd_Cyrl
      - plt_Latn
      - zsm_Latn
      - mal_Mlym
      - mlt_Latn
      - mri_Latn
      - mar_Deva
      - ell_Grek
      - khk_Cyrl
      - npi_Deva
      - nob_Latn
      - ory_Orya
      - orm
      - pes_Arab
      - pol_Latn
      - por_Latn
      - ron_Latn
      - rus_Cyrl
      - smo_Latn
      - gla_Latn
      - srp_Cyrl
      - sna_Latn
      - snd_Arab
      - sin_Sinh
      - slk_Latn
      - slv_Latn
      - som_Latn
      - spa_Latn
      - sun_Latn
      - swh_Latn
      - swe_Latn
      - tgl_Latn
      - tgk_Cyrl
      - tam_Taml
      - tat_Cyrl
      - tel_Telu
      - tha_Thai
      - tir_Ethi
      - tur_Latn
      - tuk_Latn
      - ukr_Cyrl
      - urd_Arab
      - vie_Latn
      - cym_Latn
      - wol_Latn
      - xho_Latn
      - ydd_Hebr
      - yor_Latn
      - zul_Latn
custom:
  models:
    nllb:
      url: https://model-2qjl172w.api.baseten.co/development/predict
      api_key: 
      languages:
        - ace_Arab
        - ace_Latn
        - acm_Arab
        - acq_Arab
        - aeb_Arab
        - afr_Latn
        - ajp_Arab
        - aka_Latn
        - amh_Ethi
        - apc_Arab
        - arb_Arab
        - arb_Latn
        - ars_Arab
        - ary_Arab
        - arz_Arab
        - asm_Beng
        - ast_Latn
        - awa_Deva
        - ayr_Latn
        - azb_Arab
        - azj_Latn
        - bak_Cyrl
        - bam_Latn
        - ban_Latn
        - bel_Cyrl
        - bem_Latn
        - ben_Beng
        - bho_Deva
        - bjn_Arab
        - bjn_Latn
        - bod_Tibt
        - bos_Latn
        - bug_Latn
        - bul_Cyrl
        - cat_Latn
        - ceb_Latn
        - ces_Latn
        - cjk_Latn
        - ckb_Arab
        - crh_Latn
        - cym_Latn
        - dan_Latn
        - deu_Latn
        - dik_Latn
        - dyu_Latn
        - dzo_Tibt
        - ell_Grek
        - eng_Latn
        - epo_Latn
        - est_Latn
        - eus_Latn
        - ewe_Latn
        - fao_Latn
        - fij_Latn
        - fin_Latn
        - fon_Latn
        - fra_Latn
        - fur_Latn
        - fuv_Latn
        - gla_Latn
        - gle_Latn
        - glg_Latn
        - grn_Latn
        - guj_Gujr
        - hat_Latn
        - hau_Latn
        - heb_Hebr
        - hin_Deva
        - hne_Deva
        - hrv_Latn
        - hun_Latn
        - hye_Armn
        - ibo_Latn
        - ilo_Latn
        - ind_Latn
        - isl_Latn
        - ita_Latn
        - jav_Latn
        - jpn_Jpan
        - kab_Latn
        - kac_Latn
        - kam_Latn
        - kan_Knda
        - kas_Arab
        - kas_Deva
        - kat_Geor
        - knc_Arab
        - knc_Latn
        - kaz_Cyrl
        - kbp_Latn
        - kea_Latn
        - khm_Khmr
        - kik_Latn
        - kin_Latn
        - kir_Cyrl
        - kmb_Latn
        - kmr_Latn
        - kon_Latn
        - kor_Hang
        - lao_Laoo
        - lij_Latn
        - lim_Latn
        - lin_Latn
        - lit_Latn
        - lmo_Latn
        - ltg_Latn
        - ltz_Latn
        - lua_Latn
        - lug_Latn
        - luo_Latn
        - lus_Latn
        - lvs_Latn
        - mag_Deva
        - mai_Deva
        - mal_Mlym
        - mar_Deva
        - min_Arab
        - min_Latn
        - mkd_Cyrl
        - plt_Latn
        - mlt_Latn
        - mni_Beng
        - khk_Cyrl
        - mos_Latn
        - mri_Latn
        - mya_Mymr
        - nld_Latn
        - nno_Latn
        - nob_Latn
        - npi_Deva
        - nso_Latn
        - nus_Latn
        - nya_Latn
        - oci_Latn
        - gaz_Latn
        - ory_Orya
        - pag_Latn
        - pan_Guru
        - pap_Latn
        - pes_Arab
        - pol_Latn
        - por_Latn
        - prs_Arab
        - pbt_Arab
        - quy_Latn
        - ron_Latn
        - run_Latn
        - rus_Cyrl
        - sag_Latn
        - san_Deva
        - sat_Olck
        - scn_Latn
        - shn_Mymr
        - sin_Sinh
        - slk_Latn
        - slv_Latn
        - smo_Latn
        - sna_Latn
        - snd_Arab
        - som_Latn
        - sot_Latn
        - spa_Latn
        - als_Latn
        - srd_Latn
        - srp_Cyrl
        - ssw_Latn
        - sun_Latn
        - swe_Latn
        - swh_Latn
        - szl_Latn
        - tam_Taml
        - tat_Cyrl
        - tel_Telu
        - tgk_Cyrl
        - tgl_Latn
        - tha_Thai
        - tir_Ethi
        - taq_Latn
        - taq_Tfng
        - tpi_Latn
        - tsn_Latn
        - tso_Latn
        - tuk_Latn
        - tum_Latn
        - tur_Latn
        - twi_Latn
        - tzm_Tfng
        - uig_Arab
        - ukr_Cyrl
        - umb_Latn
        - urd_Arab
        - uzn_Latn
        - vec_Latn
        - vie_Latn
        - war_Latn
        - wol_Latn
        - xho_Latn
        - ydd_Hebr
        - yor_Latn
        - yue_Hant
        - zho_Hans
        - zho_Hant
        - zsm_Latn
        - zul_Latn
    mbart:
      url: https://mbart-deployment-x1mpd2.baseten.co/development/predict
      api_key: 
      languages:
        - arb_Arab  # Arabic (ar_AR)
        - ces_Latn  # Czech (cs_CZ)
        - deu_Latn  # German (de_DE)
        - eng_Latn  # English (en_XX)
        - spa_Latn  # Spanish (es_XX)
        - est_Latn  # Estonian (et_EE)
        - fin_Latn  # Finnish (fi_FI)
        - fra_Latn  # French (fr_XX)
        - guj_Gujr  # Gujarati (gu_IN)
        - hin_Deva  # Hindi (hi_IN)
        - ita_Latn  # Italian (it_IT)
        - jpn_Jpan  # Japanese (ja_XX)
        - kaz_Cyrl  # Kazakh (kk_KZ)
        - kor_Hang  # Korean (ko_KR)
        - lit_Latn  # Lithuanian (lt_LT)
        - lvs_Latn  # Latvian (lv_LV)
        - mya_Mymr  # Burmese (my_MM)
        - npi_Deva  # Nepali (ne_NP)
        - nld_Latn  # Dutch (nl_XX)
        - ron_Latn  # Romanian (ro_RO)
        - rus_Cyrl  # Russian (ru_RU)
        - sin_Sinh  # Sinhala (si_LK)
        - tur_Latn  # Turkish (tr_TR)
        - vie_Latn  # Vietnamese (vi_VN)
        - zho_Hans  # Chinese (zh_CN)
        - afr_Latn  # Afrikaans (af_ZA)
        - azj_Latn  # Azerbaijani (az_AZ)
        - ben_Beng  # Bengali (bn_IN)
        - pes_Arab  # Persian (fa_IR)
        - heb_Hebr  # Hebrew (he_IL)
        - hrv_Latn  # Croatian (hr_HR)
        - ind_Latn  # Indonesian (id_ID)
        - kat_Geor  # Georgian (ka_GE)
        - khm_Khmr  # Khmer (km_KH)
        - mkd_Cyrl  # Macedonian (mk_MK)
        - mal_Mlym  # Malayalam (ml_IN)
        - khk_Cyrl  # Mongolian (mn_MN)
        - mar_Deva  # Marathi (mr_IN)
        - pol_Latn  # Polish (pl_PL)
        - pbt_Arab  # Pashto (ps_AF)
        - por_Latn  # Portuguese (pt_XX)
        - swe_Latn  # Swedish (sv_SE)
        - swh_Latn  # Swahili (sw_KE)
        - tam_Taml  # Tamil (ta_IN)
        - tel_Telu  # Telugu (te_IN)
        - tha_Thai  # Thai (th_TH)
        - tgl_Latn  # Tagalog (tl_XX)
        - ukr_Cyrl  # Ukrainian (uk_UA)
        - urd_Arab  # Urdu (ur_PK)
        - xho_Latn  # Xhosa (xh_ZA)
        - glg_Latn  # Galician (gl_ES)
        - slv_Latn  # Slovene (sl_SI)

